### ISSUE TITLE
Visualise Audio with muted audio 

### ISSUE THREAD

**Issue by becasmar** [foobar404/Wave.js#67]
Is there a way you could implement visualising audio while the audio tag is muted? I want the bars to jump on autoplay but the user has to unmute it for a better UX. In a previous issue, someone suggested { connectDestination: false } but that no longer works

**Comment by cyntler** [comment]
It's an interesting thing. I need something like that too.

**Comment by polomoshnov** [comment]
Instead of [this line](https://github.com/foobar404/Wave.js/blob/b729509c619d1626d3eb4c9ed3a18724a5c3d24a/src/index.ts#L63) add the following code:
```js
this._volume = this._audioContext.createGain();
// Set this to 1 if you want sound at startup 
// or implement code to set the desired value by passing it as one of the constructor's arguments 
this._volume.gain.value = 0; 
this._audioAnalyser.connect(this._volume);
this._volume.connect(this._audioContext.destination);
```
Then in order for the user to be able to turn on/off the sound by themselves add this mute/unmute method and bind it to a button/switch in your UI:
```js
public mute(): void {
  this._volume.gain.value = this._volume.gain.value === 1 ? 0 : 1;
}
```

I could prepare a PR for this if @foobar404 is interested. Let me know what you think. Thanks!

**Comment by foobar404** [comment]
Merging a fix for this right not, pass an optional mute parameter to the Wave constructor

```javascript
new Wave(audio, canvas, true)
