### ISSUE TITLE
Does not work on safari any work around for it?

### ISSUE THREAD

**Issue by vinikatyal** [foobar404/Wave.js#77]

**Comment by foobar404** [comment]
I believe the issue is with the AudioContext instance, which is used to get the frequency information from the audio. Safari wont let you create it, or start an analysis, unless the user has interacted with the window first.

maybe these will help also:
https://github.com/foobar404/Wave.js/issues/17
https://github.com/foobar404/Wave.js/issues/7

**Comment by rogeriochaves** [comment]
Hey there 👋
I opened a pull request with a fix at #84
